# Generated by Django 4.2.5 on 2023-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=20)),
                ('asignatura', models.TextField()),
                ('paralelo', models.IntegerField()),
                ('horario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.TextField()),
                ('opcion', models.IntegerField()),
                ('horario', models.ManyToManyField(to='horario.horario')),
            ],
        ),
    ]
