# Generated by Django 4.1.11 on 2023-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=20)),
                ('asignatura', models.TextField()),
                ('paralelo', models.PositiveSmallIntegerField()),
                ('horario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=200)),
                ('opcion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('horario', models.ManyToManyField(to='horario.horario')),
            ],
        ),
    ]
